# Generated by Django 4.1.5 on 2023-01-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Product',
        ),
    ]
