# Generated by Django 4.1.5 on 2023-01-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_manage', '0002_rename_service_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
