# Generated by Django 4.1.5 on 2023-01-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_manage', '0004_slider_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='featerd',
            field=models.BooleanField(default=True),
        ),
    ]
